"use client"
import { useEffect, useMemo, useState } from "react"
import { Eye, Fingerprint, ShieldCheck, SlidersHorizontal, TimerReset, Bot } from "lucide-react"
export type AntiCheatConfig={enabled:boolean;requireCamera:boolean;eyeTracking:boolean;gaze:boolean;singleTouch:boolean;warnOnAway:boolean;facePresence:boolean;multipleFaces:boolean;headPose:boolean;eyeClosure:boolean;focus:boolean;fullscreen:boolean;warningThreshold:number;suspiciousThreshold:number;cheatingThreshold:number;graceMs:number;blockMs:number;autoRestore:boolean;analysisIntervalMs:number;sensitivity:"low"|"medium"|"high";maxWarnings:number;recoveryStableMs:number;startStableMs:number;aiAssist:boolean}
export const defaultAntiCheatConfig:AntiCheatConfig={enabled:false,requireCamera:true,eyeTracking:true,gaze:true,singleTouch:true,warnOnAway:true,facePresence:true,multipleFaces:true,headPose:true,eyeClosure:true,focus:true,fullscreen:false,warningThreshold:22,suspiciousThreshold:48,cheatingThreshold:76,graceMs:2500,blockMs:8000,autoRestore:true,analysisIntervalMs:250,sensitivity:"medium",maxWarnings:3,recoveryStableMs:2200,startStableMs:1800,aiAssist:true}
type Item={itemId:string;itemType:"recitation"|"exam"|"task";label:string}
const defaults:Item[]=[{itemId:"demo-quiz",itemType:"recitation",label:"التسميع الحالي"},{itemId:"demo-quiz",itemType:"exam",label:"الاختبار الحالي"},{itemId:"demo-quiz",itemType:"task",label:"المهمة الحالية"}]
export function AntiCheatSettings({value,onChange,items=defaults}:{value:AntiCheatConfig;onChange:(v:AntiCheatConfig)=>void;items?:Item[]}){
 const [global,setGlobal]=useState(value.enabled),[overrides,setOverrides]=useState<Record<string,boolean>>({}),[status,setStatus]=useState("")
 const key=(i:Item)=>`${i.itemId}:${i.itemType}`
 useEffect(()=>{void (async()=>{try{const r=await fetch("/api/anti-cheat",{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();setGlobal(Boolean(d.global?.enabled));if(d.global?.config)onChange({...defaultAntiCheatConfig,...d.global.config,enabled:Boolean(d.global.enabled)});setOverrides(Object.fromEntries((d.items??[]).map((x:any)=>[`${x.itemId}:${x.itemType}`,Boolean(x.enabled)])))}catch{setStatus("تعذر تحميل الإعدادات من الخادم")}})()},[])
 const update=(patch:Partial<AntiCheatConfig>)=>onChange({...value,...patch})
 const save=async(enabled=global)=>{setStatus("جارٍ الحفظ...");try{const r=await fetch("/api/anti-cheat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save-global",enabled,config:{...value,enabled}})});if(!r.ok)throw new Error();setGlobal(enabled);setStatus("تم الحفظ على الخادم")}catch{setStatus("تعذر الحفظ")}}
 const rows=useMemo(()=>[{key:"requireCamera",icon:ShieldCheck,title:"إلزام الكاميرا",description:"لا تبدأ الجلسة عند رفض الكاميرا."},{key:"facePresence",icon:Eye,title:"وجود الوجه",description:"يتابع استمرار ظهور الوجه بوضوح."},{key:"multipleFaces",icon:Eye,title:"وجه واحد فقط",description:"يرصد ظهور شخص إضافي."},{key:"eyeTracking",icon:Eye,title:"النظر المباشر",description:"يتحقق من اتجاه العينين على الشاشة."},{key:"headPose",icon:Eye,title:"اتجاه الرأس",description:"يرصد إبعاد الوجه عن الشاشة."},{key:"eyeClosure",icon:Eye,title:"فتح العينين",description:"يتسامح مع الرمش الطبيعي ويرصد الإغلاق المستمر."},{key:"singleTouch",icon:Fingerprint,title:"إصبع واحد في أي مكان",description:"لا يفرض منطقة لمس محددة ولا يحتاج ضغطاً مستمراً."},{key:"focus",icon:TimerReset,title:"التركيز على الصفحة",description:"يرصد إخفاء الصفحة أو تبديل التطبيق."},{key:"aiAssist",icon:Bot,title:"مساعدة Gemini وGroq",description:"تحلل الإشارات المجمعة فقط ولا ترفع الفيديو."}] as const,[])
 const nums:[string,keyof AntiCheatConfig,number,number,boolean][]=[["المهلة (ث)","graceMs",1,60,true],["التحذيرات","maxWarnings",1,20,false],["استعادة طبيعية (ث)","recoveryStableMs",1,60,true],["مدة الحجب (ث)","blockMs",1,120,true]]
 return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-primary">تسميع / اختبار / مهمة</p><h2 className="mt-1 text-xl font-bold">إعدادات مكافحة الغش</h2><p className="mt-1 text-sm text-muted-foreground">سياسة موحدة لكل العناصر، مع زر مستقل لكل عنصر.</p></div><button type="button" aria-pressed={global} onClick={()=>{const n=!global;setGlobal(n);update({enabled:n});void save(n)}} className={`relative h-7 w-12 rounded-full ${global?"bg-primary":"bg-muted"}`}><span className={`absolute top-1 size-5 rounded-full bg-background ${global?"right-1":"right-6"}`}/></button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map(i=>{const enabled=overrides[key(i)]??global;return <div key={key(i)} className="flex items-center justify-between rounded-xl border p-3"><span>{i.label}</span><button onClick={async()=>{const next=!enabled;const r=await fetch("/api/anti-cheat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save-config",item:{itemId:i.itemId,itemType:i.itemType,enabled:next,config:value}})});if(r.ok)setOverrides(x=>({...x,[key(i)]:next}))}} className={`rounded-full px-3 py-1 text-xs ${enabled?"bg-primary text-primary-foreground":"bg-muted"}`}>{enabled?"مفعّل":"موقوف"}</button></div>})}</div><div className="mt-5 grid gap-2 md:grid-cols-2">{rows.map(({key:field,icon:Icon,title,description})=><label key={field} className="flex cursor-pointer items-center justify-between rounded-xl border p-3"><span><span className="flex items-center gap-2 font-semibold"><Icon className="size-4 text-primary"/>{title}</span><span className="block text-xs text-muted-foreground">{description}</span></span><input type="checkbox" checked={Boolean(value[field])} onChange={e=>update({[field]:e.target.checked} as Partial<AntiCheatConfig>)}/></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{nums.map(([label,field,min,max,seconds])=>{const raw=Number(value[field]);return <label key={String(field)} className="text-sm">{label}<input type="number" min={min} max={max} value={seconds?Math.round(raw/1000):raw} onChange={e=>update({[field]:(seconds?Number(e.target.value)*1000:Number(e.target.value))} as Partial<AntiCheatConfig>)} className="mt-1 w-full rounded-lg border bg-background p-2"/></label>})}</div><div className="mt-4 flex items-center justify-between"><button onClick={()=>void save()} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">حفظ السياسة</button><span className="text-xs text-muted-foreground">{status}</span></div></section>
}
export function AntiCheatSummary({config}:{config:AntiCheatConfig}){return <div className="rounded-xl border p-4"><div className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="text-primary"/>الحماية {config.enabled?"مفعّلة":"غير مفعّلة"}</div><p className="mt-2 text-xs text-muted-foreground">قرار متعدد الإشارات + سياسة خادم + استعادة تلقائية.</p></div>}
